"""Initialize database

Revision ID: 01defc72637a
Revises: 
Create Date: 2023-10-19 18:30:01.934674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01defc72637a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ActivePlayers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playerName', sa.String(), nullable=True),
    sa.Column('playerCode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cs'
    )
    op.create_table('Characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cs'
    )
    op.create_table('GameStatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cs'
    )
    op.create_table('Locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cs'
    )
    op.create_table('Rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roomName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cs'
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessionInfo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cs'
    )
    op.create_table('Weapons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weaponName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cs'
    )
    op.create_table('ActiveGames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gameStatus', sa.Integer(), nullable=True),
    sa.Column('playerCount', sa.Integer(), nullable=True),
    sa.Column('gameCode', sa.String(), nullable=True),
    sa.Column('currentPlayer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currentPlayer'], ['cs.ActivePlayers.id'], ),
    sa.ForeignKeyConstraint(['gameStatus'], ['cs.GameStatus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cs'
    )
    op.create_table('Paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationId1', sa.Integer(), nullable=True),
    sa.Column('locationId2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locationId1'], ['cs.Locations.id'], ),
    sa.ForeignKeyConstraint(['locationId2'], ['cs.Locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cs'
    )
    op.create_table('Guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('characterId', sa.Integer(), nullable=True),
    sa.Column('gameId', sa.Integer(), nullable=True),
    sa.Column('roomId', sa.Integer(), nullable=True),
    sa.Column('weaponId', sa.Integer(), nullable=True),
    sa.Column('playerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characterId'], ['cs.Characters.id'], ),
    sa.ForeignKeyConstraint(['gameId'], ['cs.ActiveGames.id'], ),
    sa.ForeignKeyConstraint(['playerId'], ['cs.ActivePlayers.id'], ),
    sa.ForeignKeyConstraint(['roomId'], ['cs.Rooms.id'], ),
    sa.ForeignKeyConstraint(['weaponId'], ['cs.Weapons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cs'
    )
    op.create_table('PlayerLocations',
    sa.Column('gameId', sa.Integer(), nullable=False),
    sa.Column('playerId', sa.Integer(), nullable=False),
    sa.Column('characterId', sa.Integer(), nullable=True),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characterId'], ['cs.Characters.id'], ),
    sa.ForeignKeyConstraint(['gameId'], ['cs.ActiveGames.id'], ),
    sa.ForeignKeyConstraint(['locationId'], ['cs.Locations.id'], ),
    sa.ForeignKeyConstraint(['playerId'], ['cs.ActivePlayers.id'], ),
    sa.PrimaryKeyConstraint('gameId', 'playerId'),
    schema='cs'
    )
    op.create_table('PlayerOrder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gameId', sa.Integer(), nullable=True),
    sa.Column('playerId', sa.Integer(), nullable=True),
    sa.Column('turn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gameId'], ['cs.ActiveGames.id'], ),
    sa.ForeignKeyConstraint(['playerId'], ['cs.ActivePlayers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cs'
    )
    op.create_table('Solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('characterId', sa.Integer(), nullable=True),
    sa.Column('gameId', sa.Integer(), nullable=True),
    sa.Column('roomId', sa.Integer(), nullable=True),
    sa.Column('weaponId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characterId'], ['cs.Characters.id'], ),
    sa.ForeignKeyConstraint(['gameId'], ['cs.ActiveGames.id'], ),
    sa.ForeignKeyConstraint(['roomId'], ['cs.Rooms.id'], ),
    sa.ForeignKeyConstraint(['weaponId'], ['cs.Weapons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cs'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Solutions', schema='cs')
    op.drop_table('PlayerOrder', schema='cs')
    op.drop_table('PlayerLocations', schema='cs')
    op.drop_table('Guesses', schema='cs')
    op.drop_table('Paths', schema='cs')
    op.drop_table('ActiveGames', schema='cs')
    op.drop_table('Weapons', schema='cs')
    op.drop_table('Users', schema='cs')
    op.drop_table('Rooms', schema='cs')
    op.drop_table('Locations', schema='cs')
    op.drop_table('GameStatus', schema='cs')
    op.drop_table('Characters', schema='cs')
    op.drop_table('ActivePlayers', schema='cs')
    # ### end Alembic commands ###
